apiVersion: v1
kind: LimitRange
metadata:
  name: healthcare-default-limits
  namespace: healthcare-backend
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 200m
      memory: 256Mi
    default:
      cpu: 1000m
      memory: 1024Mi

