apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: healthcare-backend
  labels:
    app: pgbouncer
data:
  pgbouncer.ini: |
    [databases]
    userdb = host=postgres port=5432 dbname=userdb

    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = 6432
    auth_type = scram-sha-256
    auth_user = {{AUTH_USER}}
    auth_query = SELECT usename, passwd FROM pg_shadow WHERE usename=$1
    pool_mode = transaction
    max_client_conn = 1000
    default_pool_size = 20
    min_pool_size = 5
    reserve_pool_size = 5
    reserve_pool_timeout = 5
    server_reset_query = DISCARD ALL
    server_check_delay = 15
    server_check_query = SELECT 1
    ignore_startup_parameters = extra_float_digits
    admin_users = {{AUTH_USER}}
    stats_users = {{AUTH_USER}}
    log_disconnections = 1
    log_connections = 1
    verbose = 0
    client_tls_sslmode = disable
    server_tls_sslmode = disable
